#!/usr/bin/env node

import { DesignToCodePipeline } from '../src/utils/crew';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

interface CliArgs {
  site: string;
  pages: string;
  output: string;
  stopAfter?: number;
  createPR?: boolean;
  designTokens?: string;
}

function parseArgs(args: string[]): CliArgs {
  const parsed: Partial<CliArgs> = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const [key, value] = args[i].slice(2).split('=');
      if (key === 'site') parsed.site = value;
      if (key === 'pages') parsed.pages = value;
      if (key === 'output') parsed.output = value;
      if (key === 'stopAfter') parsed.stopAfter = parseInt(value);
      if (key === 'createPR') parsed.createPR = value === 'true';
      if (key === 'designTokens') parsed.designTokens = value;
    }
  }
  return parsed as CliArgs;
}

async function createDesignReviewPR(outputPath: string, pages: string[]): Promise<void> {
  const branchName = `design-review/${path.basename(outputPath)}-wireframes`;
  const pageName = pages[0] === '/' ? 'homepage' : pages[0].replace('/', '');
  
  console.log(`🔀 Creating design review branch: ${branchName}`);
  
  try {
    // Create and checkout new branch
    execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });
    
    // Add design artifacts
    if (fs.existsSync(outputPath)) {
      execSync(`git add ${outputPath}`, { stdio: 'inherit' });
      execSync(`git commit -m "feat: wireframes for ${pageName} - ready for review"`, { stdio: 'inherit' });
      execSync(`git push -u origin ${branchName}`, { stdio: 'inherit' });
    }
    
    // Create PR body with embedded images
    const prBody = createPRBody(outputPath, pageName);
    
    // Create draft PR using GitHub CLI
    const prTitle = `🎨 Wireframe Review: ${pageName.charAt(0).toUpperCase() + pageName.slice(1)}`;
    
    try {
      const prCommand = `gh pr create --title "${prTitle}" --body "${prBody.replace(/"/g, '\\"')}" --draft --base main`;
      execSync(prCommand, { stdio: 'inherit' });
      console.log(`✅ Draft PR created for wireframe review`);
    } catch (error) {
      console.warn(`⚠️ GitHub CLI not available. Create PR manually with this body:`);
      console.log('---PR BODY---');
      console.log(prBody);
      console.log('---END PR BODY---');
    }
    
  } catch (error) {
    console.error(`❌ Failed to create design review PR: ${error}`);
    process.exit(1);
  }
}

function createPRBody(outputPath: string, pageName: string): string {
  const screenshotPath = `${outputPath}/screenshots/home.png`;
  const wireframePath = `${outputPath}/wireframes/home-wire.png`;
  const styledPath = `${outputPath}/styled/home-styled.png`;
  const jsonPath = `${outputPath}/wireframes.json`;
  
  return `# 🎨 Wireframe Review: ${pageName.charAt(0).toUpperCase() + pageName.slice(1)}

## 📋 Review Checklist
Please review the generated wireframes and styled mockups below:

- [ ] **Approve wireframes** - Layout and structure look good
- [ ] **Request changes** - Need modifications before implementation

## 🖼️ Generated Assets

### Original Screenshot
![Original Screenshot](${screenshotPath})

### Extracted Wireframe
![Wireframe](${wireframePath})

### Styled Design (GSI Orders Theme)
![Styled Design](${styledPath})

## 📄 Wireframe Data
The extracted wireframe components and metadata are available in:
- \`${jsonPath}\`

## 🚀 Next Steps

1. **Review the designs above**
2. **Check the appropriate box** in the checklist
3. **Merge this PR** if approved, or **request changes** if modifications needed
4. **Once merged**, the pipeline will automatically continue with Crews 4-8 for implementation

## ⚠️ Important Notes

- **No code has been generated yet** - this PR contains only design assets
- **Implementation will wait** until this PR is approved and merged
- **Any changes** to wireframes require rerunning Crews 1-3

---
*Generated by CrewAI Design-to-Code Pipeline*`;
}

async function main() {
  console.log('🚀 Starting Design-to-Code Pipeline with Wireframe Review Gate');
  
  const parsedArgs = parseArgs(process.argv.slice(2));
  const siteUrl = parsedArgs.site;
  const pages = parsedArgs.pages ? parsedArgs.pages.split(',') : [];
  const outputDir = parsedArgs.output;
  const stopAfter = parsedArgs.stopAfter;
  const createPR = parsedArgs.createPR !== false;
  const designTokens = parsedArgs.designTokens;

  if (!siteUrl || !pages || !outputDir) {
    console.error('❌ Missing required arguments');
    console.log('Usage: npm run design-pipeline -- --site="https://example.com" --pages="/" --output="design_output/homepage" [--stopAfter=3] [--createPR=true]');
    process.exit(1);
  }
  
  const config = {
    site: siteUrl,
    pages: pages,
    output: outputDir,
    stopAfter: stopAfter,
    designTokens: designTokens
  };
  
  const pipeline = new DesignToCodePipeline(config);
  const result = await pipeline.run();
  
  if (!result.success) {
    console.error(`❌ Pipeline failed: ${result.error}`);
    process.exit(1);
  }
  
  console.log(`✅ Pipeline completed: ${result.output}`);
  
  // If we stopped after Crew 3 and createPR is requested, create design review PR
  if (stopAfter === 3 && createPR !== false) {
    await createDesignReviewPR(outputDir, pages);
  }
  
  if (stopAfter === 3) {
    console.log('\n🔍 WIREFRAME REVIEW REQUIRED');
    console.log('👀 Review the generated wireframes in the draft PR');
    console.log('✅ Merge the PR to continue with implementation (Crews 4-8)');
    console.log('🔄 Or request changes to regenerate wireframes');
  }
}

main().catch(error => {
  console.error('❌ Pipeline execution failed:', error);
  process.exit(1);
}); 